KunstmaanMediaBundle_pagepartadmin:
    resource: '@KunstmaanPagePartBundle/Controller/PagePartAdminController.php'
    type:     annotation
    prefix:   /admin

KunstmaanMediaBundle_sir_trevor:
    resource: '@KunstmaanPagePartBundle/Controller/SirTrevorController.php'
    type:     annotation
    prefix:   /

