services:
    kunstmaan_api.service.data_transformer:
        class: Kunstmaan\ApiBundle\Service\DataTransformerService

    kunstmaan_api.service.transformers.page:
        class: Kunstmaan\ApiBundle\Service\Transformers\PageTransformer
        arguments:
            - "@doctrine.orm.default_entity_manager"
            - "@kunstmaan_api.service.data_transformer"
        tags:
            - { name: kunstmaan_api.transformer, priority: -250 }

    kunstmaan_api.service.transformers.page_part:
        class: Kunstmaan\ApiBundle\Service\Transformers\PagePartTransformer
        arguments:
            - "@doctrine.orm.default_entity_manager"
        tags:
            - { name: kunstmaan_api.transformer }

    Kunstmaan\ApiBundle\GraphQL\Schema:
        arguments:
            - "@Kunstmaan\\ApiBundle\\GraphQL\\QueryType"
            - "@Kunstmaan\\ApiBundle\\GraphQL\\MutationType"

    Kunstmaan\ApiBundle\GraphQL\MutationType:
        arguments:
            - "@Kunstmaan\\ApiBundle\\Helper\\GraphQLHelper"

    Kunstmaan\ApiBundle\GraphQL\QueryType:
        arguments:
            - "@Kunstmaan\\ApiBundle\\Helper\\GraphQLHelper"

    Kunstmaan\ApiBundle\Helper\GraphQLHelper:
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kunstmaan_api.bundles%"
            - "@kunstmaan_node.page_creator_service"
            - "@request_stack"
            - "@event_dispatcher"

    kunstmaan_api.helper.pagepart_resolver:
        class: Kunstmaan\ApiBundle\Helper\PagePartResolver